language: php
php:
  - '5.5'
install:
  composer install
script:
  phpunit --coverage-clover=coverage.xml tests
notifications:
  webhooks:
    urls:
      - http://dev.dutings.com/git/pull
    on_success: always
    on_failure: never
    on_start: never

after_success:
  - bash <(curl -s https://codecov.io/bash)