language: php
php:
  - '5.5'
install:
  composer install
before_script:
  - php -S localhost:8000 index.php &
  - sleep 3
script:
  phpunit tests
notifications:
  webhooks:
    urls:
      - http://dev.dutings.com/git/pull
    on_success: always
    on_failure: never
    on_start: never